services:
  web:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: rails s -b 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_HOST}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes: 
      - ./tmp/postgres_data:/var/lib/postgresql/data