name: Build and test

on:
  pull_request:
    branches:
      - develop

jobs:
  cucumber_test:
    runs-on: ubuntu-latest
    env:
        DEV_DB_NAME: dev_db
        DB_USERNAME: postgres_dev
        DB_PASSWORD: 543221
        TEST_DB_NAME: test_db

    services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_DB: myapp_test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
          ports:
            - 5432:5432
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

    - name: Build and test with Docker Compose
      run: |
        docker-compose build
        docker-compose up -d
        docker-compose exec web bundle exec rake db:create db:migrate
        docker-compose exec web bundle exec rspec # or your preferred testing command

    - name: Clean up
      run: |
        docker-compose down
    